apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - middleware.yaml
  - service.yaml
patches:
- target:
    kind: Deployment
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ${releaseNamespace}
- target:
    kind: Service
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ${releaseNamespace}
- target:
    kind: ConfigMap
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ${releaseNamespace}
- target:
    kind: Ingress
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ${releaseNamespace}
