---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: hello
      sourceRef:
        kind: HelmRepository
        name: hello
        namespace: ${releaseNamespace} 
      version: 0.4.0
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  releaseName: hello
  valuesFrom:
    - kind: ConfigMap
      name: hello-0.4.0-defaults
  targetNamespace: ${releaseNamespace}

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hello
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "${helmMirrorURL:=https://www.kleinloog.ch/hello-helm}"
